### ISSUE TITLE
Bug in comparison function since last change 

### ISSUE THREAD

**Issue by FranckRJ** [Qix-/tortellini#1]
https://github.com/Qix-/tortellini/blob/2cac900bf5473ac9be1af4cb6f2e2b4c1d9afd86/tortellini.hh#L118

As i understand, this function is used for == comparison, but you use `std::lexicographical_compare` than will return true if `l` is lexicographic smaller  than `r`. Even if you use `operator==` this can still happen for non-equals strings, example : https://godbolt.org/z/KLoRL9 .

**Comment by FranckRJ** [comment]
You should just use `std::equal`.

**Comment by Qix-** [comment]
Fantastic catch, that would have caused some headache later.

Thank you very much.

**Comment by FranckRJ** [comment]
https://github.com/Qix-/tortellini/commit/e62d81270758b4d7da5d9cbe6fc750c085848078#diff-f018793c8a8f1398780f8e4e1e82e39fR120

You should keep `r.end()`, because otherwise `std::equal` will go past the end of `r` if it's smaller than `l`. In your code it will never happen because it require that `l` contain a `\0` in the middle of the string (`std::string` support this) but better safe than sorry.

(@Qix- not sure if you will receive a notification for this comment because the issue is already closed so i tag you, and thanks for the rewards on reddit)

**Comment by Qix-** [comment]
It wouldn't compile for me when I tried - I'll try again.

And no problem, I appreciate the review very much. :)

**Comment by Qix-** [comment]
That overload of `std::equal` isn't available until ~~c++17~~ c++14 it appears.

Will do some more research.

**Comment by FranckRJ** [comment]
You can just check that `l.size() == r.size()` before calling `std::equal` if you don't use C++14.

**Comment by Qix-** [comment]
Man I really must be tired, that is a much better solution.

**Comment by Qix-** [comment]
Alright, hopefully that solves that :)

**Comment by Qix-** [comment]
By the way, usually you still get notifications on github even after an issue is closed. Once you participate in an issue/PR you have to manually opt-out with the notifications button on the right; the issue status doesn't affect your notifications :)

Thanks again!
