### ISSUE TITLE
need fix

### ISSUE THREAD

**Issue by ghost** [Qix-/tortellini#16]
Hi, if i use NDEBUG & RELEASE defines in my projetct, then the "strparse" function is not working properly (return only fallback value). could you make this function without try/catch construct?

![Безымянный](https://user-images.githubusercontent.com/64489444/99391555-6319e880-28eb-11eb-97ea-52684399b686.png)

**Comment by Qix-** [comment]
This doesn't make any sense. There's no reason `NDEBUG` would change behavior here, and `RELEASE` is not a macro I've ever used (let alone in Tortellini).

Going to close as it appears to be user error (that `ifndef` is not part of this codebase...). Feel free to add more reproduction details if you think this is closed in error.

**Comment by ghost** [comment]
Look at this vid: [screencast.zip](https://github.com/Qix-/tortellini/files/5553638/screencast.zip)
if i use release ver, then strparse return default value (accel == 0.0)
But in ini file accel = 0,075

**Comment by Qix-** [comment]
I'm not downloading a random zip, sorry. Please include a reproducible program that I can test.

**Comment by ghost** [comment]
Link to video: https://yadi.sk/i/j1N6VLIYpGyE1Q

**Comment by Qix-** [comment]
Like I said, I'm not interested in videos. I need a reproduction case, please.
