### ISSUE TITLE
Readme docs for running test are outdated

### ISSUE THREAD

**Issue by Qix-** [Qix-/tortellini#17]
The readme states you can run tests by running `make` but this is no longer the case; the library was switched to CMake in order to create a target and to honor the testing flags provided by CMake.

The readme should be updated to reflect this.

```shell
mkdir build && cd build
cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build .
ctest
```

The above should be tested and, if correct, updated in the readme.

**Comment by QDaily117** [comment]
Hello! I am new to open source projects. I would like to take this issue on for your project.

**Comment by Qix-** [comment]
Sure! PR welcome :)
