### ISSUE TITLE
Can not handle byte order mark at beginning of UTF-8 text files

### ISSUE THREAD

**Issue by knivil** [Qix-/tortellini#4]
Assertion in debug mode on Visual Studio 2019 if ini files contains BOM like EF BB BF at the beginning (function ltrim). Works if BOM is removed manually.

Calling code:

    std::ifstream file{ "hello.ini" };
    tortellini::ini dict;
    file >> dict;

[https://en.wikipedia.org/wiki/Byte_order_mark](url)

**Comment by Qix-** [comment]
Indeed. I've never used them myself, so if you'd like to contribute a fix then it'd be appreciated.

The non-wide BOM check here seems to be sufficient, if you'd like to PR:

https://stackoverflow.com/a/8882051
