### ISSUE TITLE
Reading a bool from a file

### ISSUE THREAD

**Issue by geekskick** [Qix-/tortellini#7]
With a file containing:
```
v = hello
```

and extracting a bool from that using
```
const auto b = ini[""]["v"] | true;
```

I would expect the fallback to be the result, but there returned value is `false`. In tortellini.hh

```
inline bool operator |(bool fallback) const {
	return _value.empty()
		? fallback
		: (
			   case_insensitive::compare(_value, "1")
			|| case_insensitive::compare(_value, "true")
			|| case_insensitive::compare(_value, "yes")
		);
}
``` 

This function only uses the fallback if the `_value` is empty, and not if the string isn't one of the valid [1|true|yes] options. This can be seen in #5 `test.cc` line 248.

**Comment by Qix-** [comment]
Great catch.

**Comment by FranckRJ** [comment]
Isn't this intended ? I thought that every non-true values are equals to false.

> `yes`, `1` and `true` are all parsable as `bool(true)`. All other values equate to `false`.

**Comment by geekskick** [comment]
In that case I think the fallback should be removed from the bool 'getter' - as it's not actually intended to be used used?

**Comment by FranckRJ** [comment]
As i understand it's for when the key isn't present in the file, not when the key has an invalid value. So it's useful.

**Comment by Qix-** [comment]
@FranckRJ is correct on second look. I was trying to remember why I did it that way - in the case of `bool`, a missing key triggers the fallback.

The documentation should definitely be updated to better describe this.
